export const routes = {
    SPLASH_SCREEN: "SplashScreen",
    AUTH_NAVIGATOR: "AuthNavigator",
    HOME_NAVIGATOR: "HomeNavigator",
    HOME_TABS: "HomeTabs",
    GET_STARTED_SCREEN: "GetStartedScreen",
    LOGIN_SCREEN: "LoginScreen",
    OTP_VERIFICATION_SCREEN: "OtpVerificationScreen",
    ONBOARDING_FEED_INTRO_SCREEN: "OnboardingFeedIntroScreen",
    ONBOARDING_CHOOSE_ROLE_SCREEN: "OnboardingChooseRoleScreen",
    CREATE_FAN_ACCOUNT_SCREEN: "CreateFanAccountScreen",
    CREATE_COMEDIAN_ACCOUNT_SCREEN: "CreateComedianAccountScreen",
    HOME_TAB: "HomeTab",
    FOLLOWING_SCREEN: "FollowingScreen",
    TOP_COMEDIANS_SCREEN: "TopComediansScreen",
    PROFILE_SCREEN: "ProfileScreen",
    PROFILE_SCREEN_MAIN: "ProfileScreenMain",
    PROFILE_FOLLOWING_SCREEN: "ProfileFollowingScreen",
    TIP_INBOX_SCREEN: "TipInboxScreen",
    PAYOUT_HISTORY_SCREEN: "PayoutHistoryScreen",
    VERIFICATION_STATUS_SCREEN: "VerificationStatusScreen",
    EARNINGS_DASHBOARD_SCREEN: "EarningsDashboardScreen",
}